[options]
girs_directories = ["../../gir-files", "../../webkit2gtk-gir-files"]
work_mode = "sys"
min_cfg_version="2.4"
library = "WebKit2WebExtension"
version = "4.1"
single_version_file = "."
target_path = "."

external_libraries = [
    "Gio",
    "GLib",
    "GObject",
]

[external_libraries]
javascriptcore4_rs = "JavaScriptCore"
soup3 = "Soup"
